// src/pages/EmailForm/formStyles.js

const formStyles = {
  container: {
    fontFamily: 'Arial, sans-serif',
    width: '100%',
    maxWidth: '500px',
    margin: '50px auto',
    padding: '30px',
    borderRadius: '10px',
    backgroundColor: '#2E2D4E',
    boxShadow: '0 4px 15px rgba(0,0,0,0.2)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '20px',
  },
  title: {
    color: '#fff',
    marginBottom: '20px',
    fontSize: '28px',
    fontWeight: 'normal',
  },
  inputGroup: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
  },

  input: {
    width: '100%',
    padding: '12px 10px',
    border: '1px solid #7a7096',
    borderRadius: '4px',
    backgroundColor: '#3a3450',
    color: '#fff',
    fontSize: '16px',
    outline: 'none',
    boxSizing: 'border-box',
  },


  addButton: {
    width: '100%',
    padding: '12px 20px',
    backgroundColor: '#6c757d',
    color: '#fff',
    border: 'none',
    borderRadius: '4px',
    fontSize: '16px',
    fontWeight: 'bold',
    cursor: 'pointer',
    marginTop: '10px',
    transition: 'background-color 0.3s ease',
  },
  pendingListContainer: {
    width: '100%',
    backgroundColor: '#3a3450',
    borderRadius: '8px',
    padding: '15px',
    marginTop: '20px',
    boxShadow: 'inset 0 1px 3px rgba(0,0,0,0.2)',
  },
  pendingListTitle: {
    color: '#fff',
    fontSize: '18px',
    marginBottom: '10px',
    textAlign: 'center',
  },
  pendingList: {
    listStyle: 'none',
    padding: '0',
    margin: '0',
    maxHeight: '200px',
    overflowY: 'auto',
    borderBottom: '1px solid #5a5076',
    paddingBottom: '10px',
    marginBottom: '10px',
  },
  pendingListItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#5a5076',
    borderRadius: '4px',
    padding: '8px 12px',
    marginBottom: '8px',
    color: '#fff',
    fontSize: '14px',
  },
  removePendingButton: {
    backgroundColor: '#dc3545',
    color: 'white',
    border: 'none',
    borderRadius: '50%',
    width: '24px',
    height: '24px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    fontSize: '12px',
    fontWeight: 'bold',
    marginLeft: '10px',
  },
  sendAllButton: {
    width: '100%',
    padding: '15px 20px',
    backgroundColor: '#a397ed',
    color: '#fff',
    border: 'none',
    borderRadius: '4px',
    fontSize: '18px',
    fontWeight: 'bold',
    cursor: 'pointer',
    marginTop: '10px',
    transition: 'background-color 0.3s ease',
  },
  showRecordsButton: {
    background: 'none',
    border: 'none',
    color: '#a397ed',
    fontSize: '16px',
    cursor: 'pointer',
    marginTop: '10px',
    textDecoration: 'none',
  },
  errorMessage: {
    color: 'red',
    fontSize: '12px',
    minHeight: '16px',
    marginTop: '5px',
    width: '100%',
    overflow: 'hidden',
    whiteSpace: 'nowrap',
    textOverflow: 'ellipsis',
    display: 'block',
    boxSizing: 'border-box'
  },

  pendingItemWrapper: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },

  pendingItemText: {
    display: 'flex',
    flexDirection: 'column',
    width: 'calc(100% - 40px)',
  },
  inputError: {
    borderColor: 'red',
  }

};

export default formStyles;
